# Generated by Django 3.0.5 on 2020-04-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200418_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='fees_in_wolrd',
            new_name='fees_in_world',
        ),
    ]
